# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Model401UnauthorizedResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=401, message: str='UNAUTHORIZED'):  # noqa: E501
        """Model401UnauthorizedResponse - a model defined in Swagger

        :param code: The code of this Model401UnauthorizedResponse.  # noqa: E501
        :type code: int
        :param message: The message of this Model401UnauthorizedResponse.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'code': int,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }
        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'Model401UnauthorizedResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The 401UnauthorizedResponse of this Model401UnauthorizedResponse.  # noqa: E501
        :rtype: Model401UnauthorizedResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this Model401UnauthorizedResponse.


        :return: The code of this Model401UnauthorizedResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this Model401UnauthorizedResponse.


        :param code: The code of this Model401UnauthorizedResponse.
        :type code: int
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this Model401UnauthorizedResponse.


        :return: The message of this Model401UnauthorizedResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Model401UnauthorizedResponse.


        :param message: The message of this Model401UnauthorizedResponse.
        :type message: str
        """

        self._message = message
