# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Model503ServerUnavailableResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=503, message: str='SERVER_UNAVAILABLE'):  # noqa: E501
        """Model503ServerUnavailableResponse - a model defined in Swagger

        :param code: The code of this Model503ServerUnavailableResponse.  # noqa: E501
        :type code: int
        :param message: The message of this Model503ServerUnavailableResponse.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'code': int,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }
        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'Model503ServerUnavailableResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The 503ServerUnavailableResponse of this Model503ServerUnavailableResponse.  # noqa: E501
        :rtype: Model503ServerUnavailableResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this Model503ServerUnavailableResponse.


        :return: The code of this Model503ServerUnavailableResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this Model503ServerUnavailableResponse.


        :param code: The code of this Model503ServerUnavailableResponse.
        :type code: int
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this Model503ServerUnavailableResponse.


        :return: The message of this Model503ServerUnavailableResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Model503ServerUnavailableResponse.


        :param message: The message of this Model503ServerUnavailableResponse.
        :type message: str
        """

        self._message = message
