# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Model400BadRequestResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=400, message: str='BAD_REQUEST', data: List[object]=None):  # noqa: E501
        """Model400BadRequestResponse - a model defined in Swagger

        :param code: The code of this Model400BadRequestResponse.  # noqa: E501
        :type code: int
        :param message: The message of this Model400BadRequestResponse.  # noqa: E501
        :type message: str
        :param data: The data of this Model400BadRequestResponse.  # noqa: E501
        :type data: List[object]
        """
        self.swagger_types = {
            'code': int,
            'message': str,
            'data': List[object]
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'data': 'data'
        }
        self._code = code
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Model400BadRequestResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The 400BadRequestResponse of this Model400BadRequestResponse.  # noqa: E501
        :rtype: Model400BadRequestResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this Model400BadRequestResponse.


        :return: The code of this Model400BadRequestResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this Model400BadRequestResponse.


        :param code: The code of this Model400BadRequestResponse.
        :type code: int
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this Model400BadRequestResponse.


        :return: The message of this Model400BadRequestResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Model400BadRequestResponse.


        :param message: The message of this Model400BadRequestResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> List[object]:
        """Gets the data of this Model400BadRequestResponse.


        :return: The data of this Model400BadRequestResponse.
        :rtype: List[object]
        """
        return self._data

    @data.setter
    def data(self, data: List[object]):
        """Sets the data of this Model400BadRequestResponse.


        :param data: The data of this Model400BadRequestResponse.
        :type data: List[object]
        """

        self._data = data
