/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MarketingManagementService);
  }
}(this, function(expect, MarketingManagementService) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Carmodelinfo', function() {
      beforeEach(function() {
        instance = new MarketingManagementService.Carmodelinfo();
      });

      it('should create an instance of Carmodelinfo', function() {
        // TODO: update the code to test Carmodelinfo
        expect(instance).to.be.a(MarketingManagementService.Carmodelinfo);
      });

      it('should have the property modelType (base name: "model_type")', function() {
        // TODO: update the code to test the property modelType
        expect(instance).to.have.property('modelType');
        // expect(instance.modelType).to.be(expectedValueLiteral);
      });

      it('should have the property modelName (base name: "model_name")', function() {
        // TODO: update the code to test the property modelName
        expect(instance).to.have.property('modelName');
        // expect(instance.modelName).to.be(expectedValueLiteral);
      });

      it('should have the property transmission (base name: "transmission")', function() {
        // TODO: update the code to test the property transmission
        expect(instance).to.have.property('transmission');
        // expect(instance.transmission).to.be(expectedValueLiteral);
      });

      it('should have the property fuelType (base name: "fuel_type")', function() {
        // TODO: update the code to test the property fuelType
        expect(instance).to.have.property('fuelType');
        // expect(instance.fuelType).to.be(expectedValueLiteral);
      });

      it('should have the property trim (base name: "trim")', function() {
        // TODO: update the code to test the property trim
        expect(instance).to.have.property('trim');
        // expect(instance.trim).to.be(expectedValueLiteral);
      });

    });
  });

}));
