/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MarketingManagementService);
  }
}(this, function(expect, MarketingManagementService) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('OfferInfo', function() {
      beforeEach(function() {
        instance = new MarketingManagementService.OfferInfo();
      });

      it('should create an instance of OfferInfo', function() {
        // TODO: update the code to test OfferInfo
        expect(instance).to.be.a(MarketingManagementService.OfferInfo);
      });

      it('should have the property discountPct (base name: "discount_pct")', function() {
        // TODO: update the code to test the property discountPct
        expect(instance).to.have.property('discountPct');
        // expect(instance.discountPct).to.be(expectedValueLiteral);
      });

      it('should have the property startDate (base name: "start_date")', function() {
        // TODO: update the code to test the property startDate
        expect(instance).to.have.property('startDate');
        // expect(instance.startDate).to.be(expectedValueLiteral);
      });

      it('should have the property endDate (base name: "end_date")', function() {
        // TODO: update the code to test the property endDate
        expect(instance).to.have.property('endDate');
        // expect(instance.endDate).to.be(expectedValueLiteral);
      });

      it('should have the property applicableModels (base name: "applicable_models")', function() {
        // TODO: update the code to test the property applicableModels
        expect(instance).to.have.property('applicableModels');
        // expect(instance.applicableModels).to.be(expectedValueLiteral);
      });

    });
  });

}));
