/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Carmodeldetails} from '../model/Carmodeldetails';
import {Carmodelinfo} from '../model/Carmodelinfo';
import {Model201CarModelCreatedResponse} from '../model/Model201CarModelCreatedResponse';
import {Model400BadRequestResponse} from '../model/Model400BadRequestResponse';
import {Model401UnauthorizedResponse} from '../model/Model401UnauthorizedResponse';
import {Model403ForbiddenResponse} from '../model/Model403ForbiddenResponse';
import {Model404NotFoundResponse} from '../model/Model404NotFoundResponse';
import {Model409ConflictResponse} from '../model/Model409ConflictResponse';
import {Model503ServerUnavailableResponse} from '../model/Model503ServerUnavailableResponse';

/**
* CarModels service.
* @module api/CarModelsApi
* @version 1.0.0
*/
export class CarModelsApi {

    /**
    * Constructs a new CarModelsApi. 
    * @alias module:api/CarModelsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addCarModel operation.
     * @callback moduleapi/CarModelsApi~addCarModelCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Model201CarModelCreatedResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add one car model
     * @param {Object} opts Optional parameters
     * @param {module:model/Carmodelinfo} opts.body Adds a car model
     * @param {module:api/CarModelsApi~addCarModelCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    addCarModel(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Model201CarModelCreatedResponse;

      return this.apiClient.callApi(
        '/cars/models', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getCarModels operation.
     * @callback moduleapi/CarModelsApi~getCarModelsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Carmodeldetails{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get details of all car models
     * @param {module:api/CarModelsApi~getCarModelsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getCarModels(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Carmodeldetails;

      return this.apiClient.callApi(
        '/cars/models', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getCarModeltype operation.
     * @callback moduleapi/CarModelsApi~getCarModeltypeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Carmodeldetails{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get details of all car models
     * @param {String} modelType 
     * @param {module:api/CarModelsApi~getCarModeltypeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getCarModeltype(modelType, callback) {
      
      let postBody = null;
      // verify the required parameter 'modelType' is set
      if (modelType === undefined || modelType === null) {
        throw new Error("Missing the required parameter 'modelType' when calling getCarModeltype");
      }

      let pathParams = {
        'model_type': modelType
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Carmodeldetails;

      return this.apiClient.callApi(
        '/cars/models/{model_type}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}