/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MarketingManagementService);
  }
}(this, function(expect, MarketingManagementService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MarketingManagementService.CarModelsApi();
  });

  describe('(package)', function() {
    describe('CarModelsApi', function() {
      describe('addCarModel', function() {
        it('should call addCarModel successfully', function(done) {
          // TODO: uncomment, update parameter values for addCarModel call and complete the assertions
          /*
          var opts = {};

          instance.addCarModel(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MarketingManagementService.Model201CarModelCreatedResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCarModels', function() {
        it('should call getCarModels successfully', function(done) {
          // TODO: uncomment getCarModels call and complete the assertions
          /*

          instance.getCarModels(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MarketingManagementService.Carmodeldetails);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCarModeltype', function() {
        it('should call getCarModeltype successfully', function(done) {
          // TODO: uncomment, update parameter values for getCarModeltype call and complete the assertions
          /*

          instance.getCarModeltype(modelType, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MarketingManagementService.Carmodeldetails);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
