/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MarketingManagementService);
  }
}(this, function(expect, MarketingManagementService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MarketingManagementService.OffersApi();
  });

  describe('(package)', function() {
    describe('OffersApi', function() {
      describe('addOffer', function() {
        it('should call addOffer successfully', function(done) {
          // TODO: uncomment, update parameter values for addOffer call and complete the assertions
          /*
          var opts = {};

          instance.addOffer(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MarketingManagementService.Model201OfferCreatedResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteOffer', function() {
        it('should call deleteOffer successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteOffer call and complete the assertions
          /*

          instance.deleteOffer(offerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MarketingManagementService.Model200OfferDeletedResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getOfferDetails', function() {
        it('should call getOfferDetails successfully', function(done) {
          // TODO: uncomment getOfferDetails call and complete the assertions
          /*

          instance.getOfferDetails(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MarketingManagementService.OfferDetails);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateOffers', function() {
        it('should call updateOffers successfully', function(done) {
          // TODO: uncomment, update parameter values for updateOffers call and complete the assertions
          /*
          var opts = {};

          instance.updateOffers(offerId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MarketingManagementService.Model200UpdateOfferResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
