/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MarketingManagementService);
  }
}(this, function(expect, MarketingManagementService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MarketingManagementService.PricesApi();
  });

  describe('(package)', function() {
    describe('PricesApi', function() {
      describe('addPrice', function() {
        it('should call addPrice successfully', function(done) {
          // TODO: uncomment, update parameter values for addPrice call and complete the assertions
          /*
          var opts = {};

          instance.addPrice(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MarketingManagementService.Model201PriceCreatedResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deletePrice', function() {
        it('should call deletePrice successfully', function(done) {
          // TODO: uncomment, update parameter values for deletePrice call and complete the assertions
          /*

          instance.deletePrice(priceId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MarketingManagementService.Model200PriceDeletedResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getPrice', function() {
        it('should call getPrice successfully', function(done) {
          // TODO: uncomment, update parameter values for getPrice call and complete the assertions
          /*

          instance.getPrice(priceId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MarketingManagementService.PriceDetails);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getPrices', function() {
        it('should call getPrices successfully', function(done) {
          // TODO: uncomment getPrices call and complete the assertions
          /*

          instance.getPrices(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MarketingManagementService.PriceDetails);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
