# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.carmodeldetails import Carmodeldetails  # noqa: F401,E501
from swagger_server import util


class Model201CarModelCreatedResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=201, message: str='Car Model created', data: Carmodeldetails=None):  # noqa: E501
        """Model201CarModelCreatedResponse - a model defined in Swagger

        :param code: The code of this Model201CarModelCreatedResponse.  # noqa: E501
        :type code: int
        :param message: The message of this Model201CarModelCreatedResponse.  # noqa: E501
        :type message: str
        :param data: The data of this Model201CarModelCreatedResponse.  # noqa: E501
        :type data: Carmodeldetails
        """
        self.swagger_types = {
            'code': int,
            'message': str,
            'data': Carmodeldetails
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'data': 'data'
        }
        self._code = code
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Model201CarModelCreatedResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The 201CarModelCreatedResponse of this Model201CarModelCreatedResponse.  # noqa: E501
        :rtype: Model201CarModelCreatedResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this Model201CarModelCreatedResponse.


        :return: The code of this Model201CarModelCreatedResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this Model201CarModelCreatedResponse.


        :param code: The code of this Model201CarModelCreatedResponse.
        :type code: int
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this Model201CarModelCreatedResponse.


        :return: The message of this Model201CarModelCreatedResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Model201CarModelCreatedResponse.


        :param message: The message of this Model201CarModelCreatedResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> Carmodeldetails:
        """Gets the data of this Model201CarModelCreatedResponse.


        :return: The data of this Model201CarModelCreatedResponse.
        :rtype: Carmodeldetails
        """
        return self._data

    @data.setter
    def data(self, data: Carmodeldetails):
        """Sets the data of this Model201CarModelCreatedResponse.


        :param data: The data of this Model201CarModelCreatedResponse.
        :type data: Carmodeldetails
        """

        self._data = data
