/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Carmodeldetails} from './model/Carmodeldetails';
import {Carmodelinfo} from './model/Carmodelinfo';
import {Model200OfferDeletedResponse} from './model/Model200OfferDeletedResponse';
import {Model200PriceDeletedResponse} from './model/Model200PriceDeletedResponse';
import {Model200UpdateOfferResponse} from './model/Model200UpdateOfferResponse';
import {Model201CarModelCreatedResponse} from './model/Model201CarModelCreatedResponse';
import {Model201OfferCreatedResponse} from './model/Model201OfferCreatedResponse';
import {Model201PriceCreatedResponse} from './model/Model201PriceCreatedResponse';
import {Model400BadRequestResponse} from './model/Model400BadRequestResponse';
import {Model401UnauthorizedResponse} from './model/Model401UnauthorizedResponse';
import {Model403ForbiddenResponse} from './model/Model403ForbiddenResponse';
import {Model404NotFoundResponse} from './model/Model404NotFoundResponse';
import {Model409ConflictResponse} from './model/Model409ConflictResponse';
import {Model503ServerUnavailableResponse} from './model/Model503ServerUnavailableResponse';
import {OfferDetails} from './model/OfferDetails';
import {OfferInfo} from './model/OfferInfo';
import {PriceDetails} from './model/PriceDetails';
import {PriceInfo} from './model/PriceInfo';
import {UpdateOfferInfo} from './model/UpdateOfferInfo';
import {CarModelsApi} from './api/CarModelsApi';
import {OffersApi} from './api/OffersApi';
import {PricesApi} from './api/PricesApi';

/**
* A_service_for_adding_carmodels_offers_and_prices_for_cars.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MarketingManagementService = require('index'); // See note below*.
* var xxxSvc = new MarketingManagementService.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MarketingManagementService.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MarketingManagementService.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MarketingManagementService.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Carmodeldetails model constructor.
     * @property {module:model/Carmodeldetails}
     */
    Carmodeldetails,

    /**
     * The Carmodelinfo model constructor.
     * @property {module:model/Carmodelinfo}
     */
    Carmodelinfo,

    /**
     * The Model200OfferDeletedResponse model constructor.
     * @property {module:model/Model200OfferDeletedResponse}
     */
    Model200OfferDeletedResponse,

    /**
     * The Model200PriceDeletedResponse model constructor.
     * @property {module:model/Model200PriceDeletedResponse}
     */
    Model200PriceDeletedResponse,

    /**
     * The Model200UpdateOfferResponse model constructor.
     * @property {module:model/Model200UpdateOfferResponse}
     */
    Model200UpdateOfferResponse,

    /**
     * The Model201CarModelCreatedResponse model constructor.
     * @property {module:model/Model201CarModelCreatedResponse}
     */
    Model201CarModelCreatedResponse,

    /**
     * The Model201OfferCreatedResponse model constructor.
     * @property {module:model/Model201OfferCreatedResponse}
     */
    Model201OfferCreatedResponse,

    /**
     * The Model201PriceCreatedResponse model constructor.
     * @property {module:model/Model201PriceCreatedResponse}
     */
    Model201PriceCreatedResponse,

    /**
     * The Model400BadRequestResponse model constructor.
     * @property {module:model/Model400BadRequestResponse}
     */
    Model400BadRequestResponse,

    /**
     * The Model401UnauthorizedResponse model constructor.
     * @property {module:model/Model401UnauthorizedResponse}
     */
    Model401UnauthorizedResponse,

    /**
     * The Model403ForbiddenResponse model constructor.
     * @property {module:model/Model403ForbiddenResponse}
     */
    Model403ForbiddenResponse,

    /**
     * The Model404NotFoundResponse model constructor.
     * @property {module:model/Model404NotFoundResponse}
     */
    Model404NotFoundResponse,

    /**
     * The Model409ConflictResponse model constructor.
     * @property {module:model/Model409ConflictResponse}
     */
    Model409ConflictResponse,

    /**
     * The Model503ServerUnavailableResponse model constructor.
     * @property {module:model/Model503ServerUnavailableResponse}
     */
    Model503ServerUnavailableResponse,

    /**
     * The OfferDetails model constructor.
     * @property {module:model/OfferDetails}
     */
    OfferDetails,

    /**
     * The OfferInfo model constructor.
     * @property {module:model/OfferInfo}
     */
    OfferInfo,

    /**
     * The PriceDetails model constructor.
     * @property {module:model/PriceDetails}
     */
    PriceDetails,

    /**
     * The PriceInfo model constructor.
     * @property {module:model/PriceInfo}
     */
    PriceInfo,

    /**
     * The UpdateOfferInfo model constructor.
     * @property {module:model/UpdateOfferInfo}
     */
    UpdateOfferInfo,

    /**
    * The CarModelsApi service constructor.
    * @property {module:api/CarModelsApi}
    */
    CarModelsApi,

    /**
    * The OffersApi service constructor.
    * @property {module:api/OffersApi}
    */
    OffersApi,

    /**
    * The PricesApi service constructor.
    * @property {module:api/PricesApi}
    */
    PricesApi
};
