/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Carmodelinfo} from './Carmodelinfo';

/**
 * The Carmodeldetails model module.
 * @module model/Carmodeldetails
 * @version 1.0.0
 */
export class Carmodeldetails extends Carmodelinfo {
  /**
   * Constructs a new <code>Carmodeldetails</code>.
   * @alias module:model/Carmodeldetails
   * @class
   * @extends module:model/Carmodelinfo
   * @param modelType {} 
   * @param modelName {} 
   * @param transmission {} 
   * @param fuelType {} 
   * @param trim {} 
   */
  constructor(modelType, modelName, transmission, fuelType, trim) {
    super(modelType, modelName, transmission, fuelType, trim);
  }

  /**
   * Constructs a <code>Carmodeldetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Carmodeldetails} obj Optional instance to populate.
   * @return {module:model/Carmodeldetails} The populated <code>Carmodeldetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Carmodeldetails();
      Carmodelinfo.constructFromObject(data, obj);
      if (data.hasOwnProperty('model_id'))
        obj.modelId = ApiClient.convertToType(data['model_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} modelId
 */
Carmodeldetails.prototype.modelId = undefined;

