/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Model400BadRequestResponse model module.
 * @module model/Model400BadRequestResponse
 * @version 1.0.0
 */
export class Model400BadRequestResponse {
  /**
   * Constructs a new <code>Model400BadRequestResponse</code>.
   * @alias module:model/Model400BadRequestResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Model400BadRequestResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Model400BadRequestResponse} obj Optional instance to populate.
   * @return {module:model/Model400BadRequestResponse} The populated <code>Model400BadRequestResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Model400BadRequestResponse();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [Object]);
    }
    return obj;
  }
}

/**
 * @member {Number} code
 * @default 400
 */
Model400BadRequestResponse.prototype.code = 400;

/**
 * @member {String} message
 * @default 'BAD_REQUEST'
 */
Model400BadRequestResponse.prototype.message = 'BAD_REQUEST';

/**
 * @member {Array.<Object>} data
 */
Model400BadRequestResponse.prototype.data = undefined;

