/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OfferInfo model module.
 * @module model/OfferInfo
 * @version 1.0.0
 */
export class OfferInfo {
  /**
   * Constructs a new <code>OfferInfo</code>.
   * @alias module:model/OfferInfo
   * @class
   * @param discountPct {Number} 
   * @param startDate {Number} 
   * @param endDate {Number} 
   * @param applicableModels {Array.<String>} 
   */
  constructor(discountPct, startDate, endDate, applicableModels) {
    this.discountPct = discountPct;
    this.startDate = startDate;
    this.endDate = endDate;
    this.applicableModels = applicableModels;
  }

  /**
   * Constructs a <code>OfferInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OfferInfo} obj Optional instance to populate.
   * @return {module:model/OfferInfo} The populated <code>OfferInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OfferInfo();
      if (data.hasOwnProperty('discount_pct'))
        obj.discountPct = ApiClient.convertToType(data['discount_pct'], 'Number');
      if (data.hasOwnProperty('start_date'))
        obj.startDate = ApiClient.convertToType(data['start_date'], 'Number');
      if (data.hasOwnProperty('end_date'))
        obj.endDate = ApiClient.convertToType(data['end_date'], 'Number');
      if (data.hasOwnProperty('applicable_models'))
        obj.applicableModels = ApiClient.convertToType(data['applicable_models'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Number} discountPct
 */
OfferInfo.prototype.discountPct = undefined;

/**
 * @member {Number} startDate
 */
OfferInfo.prototype.startDate = undefined;

/**
 * @member {Number} endDate
 */
OfferInfo.prototype.endDate = undefined;

/**
 * @member {Array.<String>} applicableModels
 */
OfferInfo.prototype.applicableModels = undefined;

