/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OfferInfo} from './OfferInfo';

/**
 * The OfferDetails model module.
 * @module model/OfferDetails
 * @version 1.0.0
 */
export class OfferDetails extends OfferInfo {
  /**
   * Constructs a new <code>OfferDetails</code>.
   * @alias module:model/OfferDetails
   * @class
   * @extends module:model/OfferInfo
   * @param discountPct {} 
   * @param startDate {} 
   * @param endDate {} 
   * @param applicableModels {} 
   */
  constructor(discountPct, startDate, endDate, applicableModels) {
    super(discountPct, startDate, endDate, applicableModels);
  }

  /**
   * Constructs a <code>OfferDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OfferDetails} obj Optional instance to populate.
   * @return {module:model/OfferDetails} The populated <code>OfferDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OfferDetails();
      OfferInfo.constructFromObject(data, obj);
      if (data.hasOwnProperty('offer_id'))
        obj.offerId = ApiClient.convertToType(data['offer_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} offerId
 */
OfferDetails.prototype.offerId = undefined;

