/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PriceInfo model module.
 * @module model/PriceInfo
 * @version 1.0.0
 */
export class PriceInfo {
  /**
   * Constructs a new <code>PriceInfo</code>.
   * @alias module:model/PriceInfo
   * @class
   * @param modelId {String} 
   * @param price {Number} 
   * @param startDate {String} 
   * @param endDate {String} 
   */
  constructor(modelId, price, startDate, endDate) {
    this.modelId = modelId;
    this.price = price;
    this.startDate = startDate;
    this.endDate = endDate;
  }

  /**
   * Constructs a <code>PriceInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PriceInfo} obj Optional instance to populate.
   * @return {module:model/PriceInfo} The populated <code>PriceInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PriceInfo();
      if (data.hasOwnProperty('model_id'))
        obj.modelId = ApiClient.convertToType(data['model_id'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('start_date'))
        obj.startDate = ApiClient.convertToType(data['start_date'], 'String');
      if (data.hasOwnProperty('end_date'))
        obj.endDate = ApiClient.convertToType(data['end_date'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} modelId
 */
PriceInfo.prototype.modelId = undefined;

/**
 * @member {Number} price
 */
PriceInfo.prototype.price = undefined;

/**
 * @member {String} startDate
 */
PriceInfo.prototype.startDate = undefined;

/**
 * @member {String} endDate
 */
PriceInfo.prototype.endDate = undefined;

