/*
 * Marketing Management Service
 * A service for adding carmodels, offers and prices for cars
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UpdateOfferInfo model module.
 * @module model/UpdateOfferInfo
 * @version 1.0.0
 */
export class UpdateOfferInfo {
  /**
   * Constructs a new <code>UpdateOfferInfo</code>.
   * @alias module:model/UpdateOfferInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UpdateOfferInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateOfferInfo} obj Optional instance to populate.
   * @return {module:model/UpdateOfferInfo} The populated <code>UpdateOfferInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateOfferInfo();
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>key</code> property.
 * @enum {String}
 * @readonly
 */
UpdateOfferInfo.KeyEnum = {
  /**
   * value: "discount_pct"
   * @const
   */
  discountPct: "discount_pct",

  /**
   * value: "start_date"
   * @const
   */
  startDate: "start_date",

  /**
   * value: "end_date"
   * @const
   */
  endDate: "end_date",

  /**
   * value: "applicable_models"
   * @const
   */
  applicableModels: "applicable_models"
};
/**
 * @member {module:model/UpdateOfferInfo.KeyEnum} key
 */
UpdateOfferInfo.prototype.key = undefined;

/**
 * @member {String} value
 */
UpdateOfferInfo.prototype.value = undefined;

